In [8]:
# 加载numpy包
from numpy import *

In [10]:
# 建立4 * 4 的随机数组
random.rand(4,4)

array([[0.87265983, 0.6030731 , 0.28037338, 0.00612305],
       [0.50537515, 0.72621643, 0.0555965 , 0.62197328],
       [0.71163856, 0.87279559, 0.31835076, 0.64682403],
       [0.18241354, 0.85533783, 0.60273858, 0.57536832]])

In [13]:
# 把数组转换为矩阵形式
randomMat = mat(random.rand(4,4))
randomMat

matrix([[0.71647154, 0.08096044, 0.86774614, 0.92962049],
        [0.83575431, 0.69311242, 0.54278986, 0.29398925],
        [0.94707637, 0.9608886 , 0.46597507, 0.12273448],
        [0.15488375, 0.44665553, 0.33903483, 0.20063242]])

In [15]:
# 求randomMat的逆矩阵
invRandMat = randomMat.I
invRandMat

matrix([[  0.59927696,  -0.84930979,   1.78072833,  -2.62155518],
        [  3.27317465, -16.58568103,  11.85133659,   1.8872029 ],
        [-10.68004137,  46.90745309, -33.51978978,   1.25668758],
        [ 10.29796796, -41.68633435,  28.8841926 ,   0.68306918]])

In [16]:
# 计算矩阵与其逆矩阵的乘积
randomMat * invRandMat

matrix([[ 1.00000000e+00,  7.54951657e-15,  1.77635684e-15,
          2.22044605e-16],
        [ 4.44089210e-16,  1.00000000e+00,  1.77635684e-15,
          0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
          1.11022302e-16],
        [-2.22044605e-16, -2.66453526e-15,  1.77635684e-15,
          1.00000000e+00]])

正常来说，矩阵与逆矩阵的乘积应为对角线为1的矩阵，其他地方为0，但上面的结果呈现的矩阵其他地方值不为0且值非常小，这是电脑处理误差产生的结果。

In [17]:
# 计算误差
myEye = randomMat * invRandMat
# eye(4) 形成4 * 4的单位矩阵
myEye - eye(4)

matrix([[-1.22124533e-15,  7.54951657e-15,  1.77635684e-15,
          2.22044605e-16],
        [ 4.44089210e-16,  1.77635684e-15,  1.77635684e-15,
          0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          1.11022302e-16],
        [-2.22044605e-16, -2.66453526e-15,  1.77635684e-15,
          0.00000000e+00]])